### ISSUE TITLE
Import SDK 

### ISSUE THREAD

**Issue by joaodematejr** [mercadolibre/point-mainapp-demo-android#33]
I'm importing the SDK but when I start it the app closes and shows this error

FATAL EXCEPTION: main  Process: br.com.yuzer.pos.debug, PID: 6124
  java.lang.RuntimeException: Unable to create application br.com.yuzer.pos.application.YuzerApplication: java.lang.SecurityException: The SDK you are using is not valid for non-launcher applications.
![Captura de Tela 2024-02-14 às 14 52 44](https://github.com/mercadolibre/point-mainapp-demo-android/assets/17418041/32ff82df-ac44-4a4d-9ab8-80ad5296aa79)
![Captura de Tela 2024-02-14 às 14 52 54](https://github.com/mercadolibre/point-mainapp-demo-android/assets/17418041/c82ab608-26ab-4aa8-b66f-93fc86ecc71b)
![Captura de Tela 2024-02-14 às 14 53 20](https://github.com/mercadolibre/point-mainapp-demo-android/assets/17418041/47a76924-d32e-4844-b1d3-f8cb67eb2606)

**Comment by jonathan-botero-meli** [comment]
For MP intregrations, the third App must be launcher. That can be configured into the manifest, adding the <category android:name="android.intent.category.HOME" /> for the entry point activity.
